# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/ts_common_msgs/proto_custom_msgs/collect/tscompressedimage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.ts_common_msgs.proto_std_msgs import Header_pb2 as modules_dot_ts__common__msgs_dot_proto__std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/ts_common_msgs/proto_custom_msgs/collect/tscompressedimage.proto',
  package='tars.tscamera_msg',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nHmodules/ts_common_msgs/proto_custom_msgs/collect/tscompressedimage.proto\x12\x11tars.tscamera_msg\x1a\x32modules/ts_common_msgs/proto_std_msgs/Header.proto\"\xf4\x02\n\x11Tscompressedimage\x12%\n\x06header\x18\x01 \x02(\x0b\x32\x15.tars.std_msgs.Header\x12\x37\n\x04type\x18\x02 \x02(\x0e\x32).tars.tscamera_msg.Tscompressedimage.TYPE\x12\x0c\n\x04\x64\x61ta\x18\x03 \x02(\x0c\x12W\n\x0b\x61ttach_type\x18\x04 \x01(\x0e\x32\x35.tars.tscamera_msg.Tscompressedimage.CLIP_ATTACH_TYPE:\x0b\x43LIP_BELONG\x12\x1a\n\x12target_expose_time\x18\x05 \x01(\x05\x12\x18\n\x10real_expose_time\x18\x06 \x01(\x05\"(\n\x04TYPE\x12\x08\n\x04JPEG\x10\x00\x12\n\n\x06H265_I\x10\x01\x12\n\n\x06H265_P\x10\x02\"8\n\x10\x43LIP_ATTACH_TYPE\x12\x13\n\x0f\x43LIP_NOT_BELONG\x10\x00\x12\x0f\n\x0b\x43LIP_BELONG\x10\x01\"t\n\x15TscompressedimageInfo\x12%\n\x06header\x18\x01 \x02(\x0b\x32\x15.tars.std_msgs.Header\x12\x1a\n\x12target_expose_time\x18\x02 \x01(\x05\x12\x18\n\x10real_expose_time\x18\x03 \x01(\x05'
  ,
  dependencies=[modules_dot_ts__common__msgs_dot_proto__std__msgs_dot_Header__pb2.DESCRIPTOR,])



_TSCOMPRESSEDIMAGE_TYPE = _descriptor.EnumDescriptor(
  name='TYPE',
  full_name='tars.tscamera_msg.Tscompressedimage.TYPE',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JPEG', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='H265_I', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='H265_P', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=422,
  serialized_end=462,
)
_sym_db.RegisterEnumDescriptor(_TSCOMPRESSEDIMAGE_TYPE)

_TSCOMPRESSEDIMAGE_CLIP_ATTACH_TYPE = _descriptor.EnumDescriptor(
  name='CLIP_ATTACH_TYPE',
  full_name='tars.tscamera_msg.Tscompressedimage.CLIP_ATTACH_TYPE',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLIP_NOT_BELONG', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CLIP_BELONG', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=464,
  serialized_end=520,
)
_sym_db.RegisterEnumDescriptor(_TSCOMPRESSEDIMAGE_CLIP_ATTACH_TYPE)


_TSCOMPRESSEDIMAGE = _descriptor.Descriptor(
  name='Tscompressedimage',
  full_name='tars.tscamera_msg.Tscompressedimage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='tars.tscamera_msg.Tscompressedimage.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='tars.tscamera_msg.Tscompressedimage.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='tars.tscamera_msg.Tscompressedimage.data', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attach_type', full_name='tars.tscamera_msg.Tscompressedimage.attach_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_expose_time', full_name='tars.tscamera_msg.Tscompressedimage.target_expose_time', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='real_expose_time', full_name='tars.tscamera_msg.Tscompressedimage.real_expose_time', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TSCOMPRESSEDIMAGE_TYPE,
    _TSCOMPRESSEDIMAGE_CLIP_ATTACH_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=520,
)


_TSCOMPRESSEDIMAGEINFO = _descriptor.Descriptor(
  name='TscompressedimageInfo',
  full_name='tars.tscamera_msg.TscompressedimageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='tars.tscamera_msg.TscompressedimageInfo.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_expose_time', full_name='tars.tscamera_msg.TscompressedimageInfo.target_expose_time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='real_expose_time', full_name='tars.tscamera_msg.TscompressedimageInfo.real_expose_time', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=522,
  serialized_end=638,
)

_TSCOMPRESSEDIMAGE.fields_by_name['header'].message_type = modules_dot_ts__common__msgs_dot_proto__std__msgs_dot_Header__pb2._HEADER
_TSCOMPRESSEDIMAGE.fields_by_name['type'].enum_type = _TSCOMPRESSEDIMAGE_TYPE
_TSCOMPRESSEDIMAGE.fields_by_name['attach_type'].enum_type = _TSCOMPRESSEDIMAGE_CLIP_ATTACH_TYPE
_TSCOMPRESSEDIMAGE_TYPE.containing_type = _TSCOMPRESSEDIMAGE
_TSCOMPRESSEDIMAGE_CLIP_ATTACH_TYPE.containing_type = _TSCOMPRESSEDIMAGE
_TSCOMPRESSEDIMAGEINFO.fields_by_name['header'].message_type = modules_dot_ts__common__msgs_dot_proto__std__msgs_dot_Header__pb2._HEADER
DESCRIPTOR.message_types_by_name['Tscompressedimage'] = _TSCOMPRESSEDIMAGE
DESCRIPTOR.message_types_by_name['TscompressedimageInfo'] = _TSCOMPRESSEDIMAGEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tscompressedimage = _reflection.GeneratedProtocolMessageType('Tscompressedimage', (_message.Message,), {
  'DESCRIPTOR' : _TSCOMPRESSEDIMAGE,
  '__module__' : 'modules.ts_common_msgs.proto_custom_msgs.collect.tscompressedimage_pb2'
  # @@protoc_insertion_point(class_scope:tars.tscamera_msg.Tscompressedimage)
  })
_sym_db.RegisterMessage(Tscompressedimage)

TscompressedimageInfo = _reflection.GeneratedProtocolMessageType('TscompressedimageInfo', (_message.Message,), {
  'DESCRIPTOR' : _TSCOMPRESSEDIMAGEINFO,
  '__module__' : 'modules.ts_common_msgs.proto_custom_msgs.collect.tscompressedimage_pb2'
  # @@protoc_insertion_point(class_scope:tars.tscamera_msg.TscompressedimageInfo)
  })
_sym_db.RegisterMessage(TscompressedimageInfo)


# @@protoc_insertion_point(module_scope)
