# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/ts_common_msgs/proto_std_msgs/Header.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.ts_common_msgs.proto_basic_msgs import time_pb2 as modules_dot_ts__common__msgs_dot_proto__basic__msgs_dot_time__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/ts_common_msgs/proto_std_msgs/Header.proto',
  package='tars.std_msgs',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n2modules/ts_common_msgs/proto_std_msgs/Header.proto\x12\rtars.std_msgs\x1a\x32modules/ts_common_msgs/proto_basic_msgs/time.proto\"M\n\x06Header\x12\x0b\n\x03seq\x18\x01 \x02(\r\x12$\n\x05stamp\x18\x02 \x02(\x0b\x32\x15.tars.basic_msgs.time\x12\x10\n\x08\x66rame_id\x18\x03 \x02(\t'
  ,
  dependencies=[modules_dot_ts__common__msgs_dot_proto__basic__msgs_dot_time__pb2.DESCRIPTOR,])




_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='tars.std_msgs.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='tars.std_msgs.Header.seq', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stamp', full_name='tars.std_msgs.Header.stamp', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='tars.std_msgs.Header.frame_id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=198,
)

_HEADER.fields_by_name['stamp'].message_type = modules_dot_ts__common__msgs_dot_proto__basic__msgs_dot_time__pb2._TIME
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'modules.ts_common_msgs.proto_std_msgs.Header_pb2'
  # @@protoc_insertion_point(class_scope:tars.std_msgs.Header)
  })
_sym_db.RegisterMessage(Header)


# @@protoc_insertion_point(module_scope)
