# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/ts_common_msgs/proto_visual_tactile_msgs/VisualTactileSensor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.ts_common_msgs.proto_std_msgs import Header_pb2 as modules_dot_ts__common__msgs_dot_proto__std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/ts_common_msgs/proto_visual_tactile_msgs/VisualTactileSensor.proto',
  package='tars.visual_tactile_msgs',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nJmodules/ts_common_msgs/proto_visual_tactile_msgs/VisualTactileSensor.proto\x12\x18tars.visual_tactile_msgs\x1a\x32modules/ts_common_msgs/proto_std_msgs/Header.proto\"\x92\x07\n\x13VisualTactileSensor\x12%\n\x06header\x18\x01 \x02(\x0b\x32\x15.tars.std_msgs.Header\x12\x0f\n\x07rectify\x18\x02 \x01(\x0c\x12\x16\n\x0erectify_height\x18\x03 \x01(\r\x12\x15\n\rrectify_width\x18\x04 \x01(\r\x12\x18\n\x10rectify_channels\x18\x05 \x01(\r\x12\x12\n\ndifference\x18\x06 \x01(\x0c\x12\x19\n\x11\x64ifference_height\x18\x07 \x01(\r\x12\x18\n\x10\x64ifference_width\x18\x08 \x01(\r\x12\x1b\n\x13\x64ifference_channels\x18\t \x01(\r\x12\r\n\x05\x64\x65pth\x18\n \x01(\x0c\x12\x14\n\x0c\x64\x65pth_height\x18\x0b \x01(\r\x12\x13\n\x0b\x64\x65pth_width\x18\x0c \x01(\r\x12\r\n\x05\x66orce\x18\r \x01(\x0c\x12\x12\n\nforce_dim0\x18\x0e \x01(\r\x12\x12\n\nforce_dim1\x18\x0f \x01(\r\x12\x12\n\nforce_dim2\x18\x10 \x01(\r\x12\x12\n\nforce_norm\x18\x11 \x01(\x0c\x12\x17\n\x0f\x66orce_norm_dim0\x18\x12 \x01(\r\x12\x17\n\x0f\x66orce_norm_dim1\x18\x13 \x01(\r\x12\x17\n\x0f\x66orce_norm_dim2\x18\x14 \x01(\r\x12\x17\n\x0f\x66orce_resultant\x18\x15 \x01(\x0c\x12\x1b\n\x13\x66orce_resultant_dim\x18\x16 \x01(\r\x12\x11\n\tmarker_2d\x18\x17 \x01(\x0c\x12\x16\n\x0emarker_2d_dim0\x18\x18 \x01(\r\x12\x16\n\x0emarker_2d_dim1\x18\x19 \x01(\r\x12\x16\n\x0emarker_2d_dim2\x18\x1a \x01(\r\x12\x0f\n\x07mesh_3d\x18\x1b \x01(\x0c\x12\x14\n\x0cmesh_3d_dim0\x18\x1c \x01(\r\x12\x14\n\x0cmesh_3d_dim1\x18\x1d \x01(\r\x12\x14\n\x0cmesh_3d_dim2\x18\x1e \x01(\r\x12\x14\n\x0cmesh_3d_init\x18\x1f \x01(\x0c\x12\x19\n\x11mesh_3d_init_dim0\x18  \x01(\r\x12\x19\n\x11mesh_3d_init_dim1\x18! \x01(\r\x12\x19\n\x11mesh_3d_init_dim2\x18\" \x01(\r\x12\x14\n\x0cmesh_3d_flow\x18# \x01(\x0c\x12\x19\n\x11mesh_3d_flow_dim0\x18$ \x01(\r\x12\x19\n\x11mesh_3d_flow_dim1\x18% \x01(\r\x12\x19\n\x11mesh_3d_flow_dim2\x18& \x01(\r'
  ,
  dependencies=[modules_dot_ts__common__msgs_dot_proto__std__msgs_dot_Header__pb2.DESCRIPTOR,])




_VISUALTACTILESENSOR = _descriptor.Descriptor(
  name='VisualTactileSensor',
  full_name='tars.visual_tactile_msgs.VisualTactileSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='tars.visual_tactile_msgs.VisualTactileSensor.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rectify', full_name='tars.visual_tactile_msgs.VisualTactileSensor.rectify', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rectify_height', full_name='tars.visual_tactile_msgs.VisualTactileSensor.rectify_height', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rectify_width', full_name='tars.visual_tactile_msgs.VisualTactileSensor.rectify_width', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rectify_channels', full_name='tars.visual_tactile_msgs.VisualTactileSensor.rectify_channels', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='difference', full_name='tars.visual_tactile_msgs.VisualTactileSensor.difference', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='difference_height', full_name='tars.visual_tactile_msgs.VisualTactileSensor.difference_height', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='difference_width', full_name='tars.visual_tactile_msgs.VisualTactileSensor.difference_width', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='difference_channels', full_name='tars.visual_tactile_msgs.VisualTactileSensor.difference_channels', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='depth', full_name='tars.visual_tactile_msgs.VisualTactileSensor.depth', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='depth_height', full_name='tars.visual_tactile_msgs.VisualTactileSensor.depth_height', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='depth_width', full_name='tars.visual_tactile_msgs.VisualTactileSensor.depth_width', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='force', full_name='tars.visual_tactile_msgs.VisualTactileSensor.force', index=12,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='force_dim0', full_name='tars.visual_tactile_msgs.VisualTactileSensor.force_dim0', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='force_dim1', full_name='tars.visual_tactile_msgs.VisualTactileSensor.force_dim1', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='force_dim2', full_name='tars.visual_tactile_msgs.VisualTactileSensor.force_dim2', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='force_norm', full_name='tars.visual_tactile_msgs.VisualTactileSensor.force_norm', index=16,
      number=17, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='force_norm_dim0', full_name='tars.visual_tactile_msgs.VisualTactileSensor.force_norm_dim0', index=17,
      number=18, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='force_norm_dim1', full_name='tars.visual_tactile_msgs.VisualTactileSensor.force_norm_dim1', index=18,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='force_norm_dim2', full_name='tars.visual_tactile_msgs.VisualTactileSensor.force_norm_dim2', index=19,
      number=20, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='force_resultant', full_name='tars.visual_tactile_msgs.VisualTactileSensor.force_resultant', index=20,
      number=21, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='force_resultant_dim', full_name='tars.visual_tactile_msgs.VisualTactileSensor.force_resultant_dim', index=21,
      number=22, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='marker_2d', full_name='tars.visual_tactile_msgs.VisualTactileSensor.marker_2d', index=22,
      number=23, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='marker_2d_dim0', full_name='tars.visual_tactile_msgs.VisualTactileSensor.marker_2d_dim0', index=23,
      number=24, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='marker_2d_dim1', full_name='tars.visual_tactile_msgs.VisualTactileSensor.marker_2d_dim1', index=24,
      number=25, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='marker_2d_dim2', full_name='tars.visual_tactile_msgs.VisualTactileSensor.marker_2d_dim2', index=25,
      number=26, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mesh_3d', full_name='tars.visual_tactile_msgs.VisualTactileSensor.mesh_3d', index=26,
      number=27, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mesh_3d_dim0', full_name='tars.visual_tactile_msgs.VisualTactileSensor.mesh_3d_dim0', index=27,
      number=28, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mesh_3d_dim1', full_name='tars.visual_tactile_msgs.VisualTactileSensor.mesh_3d_dim1', index=28,
      number=29, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mesh_3d_dim2', full_name='tars.visual_tactile_msgs.VisualTactileSensor.mesh_3d_dim2', index=29,
      number=30, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mesh_3d_init', full_name='tars.visual_tactile_msgs.VisualTactileSensor.mesh_3d_init', index=30,
      number=31, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mesh_3d_init_dim0', full_name='tars.visual_tactile_msgs.VisualTactileSensor.mesh_3d_init_dim0', index=31,
      number=32, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mesh_3d_init_dim1', full_name='tars.visual_tactile_msgs.VisualTactileSensor.mesh_3d_init_dim1', index=32,
      number=33, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mesh_3d_init_dim2', full_name='tars.visual_tactile_msgs.VisualTactileSensor.mesh_3d_init_dim2', index=33,
      number=34, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mesh_3d_flow', full_name='tars.visual_tactile_msgs.VisualTactileSensor.mesh_3d_flow', index=34,
      number=35, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mesh_3d_flow_dim0', full_name='tars.visual_tactile_msgs.VisualTactileSensor.mesh_3d_flow_dim0', index=35,
      number=36, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mesh_3d_flow_dim1', full_name='tars.visual_tactile_msgs.VisualTactileSensor.mesh_3d_flow_dim1', index=36,
      number=37, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mesh_3d_flow_dim2', full_name='tars.visual_tactile_msgs.VisualTactileSensor.mesh_3d_flow_dim2', index=37,
      number=38, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=1071,
)

_VISUALTACTILESENSOR.fields_by_name['header'].message_type = modules_dot_ts__common__msgs_dot_proto__std__msgs_dot_Header__pb2._HEADER
DESCRIPTOR.message_types_by_name['VisualTactileSensor'] = _VISUALTACTILESENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VisualTactileSensor = _reflection.GeneratedProtocolMessageType('VisualTactileSensor', (_message.Message,), {
  'DESCRIPTOR' : _VISUALTACTILESENSOR,
  '__module__' : 'modules.ts_common_msgs.proto_visual_tactile_msgs.VisualTactileSensor_pb2'
  # @@protoc_insertion_point(class_scope:tars.visual_tactile_msgs.VisualTactileSensor)
  })
_sym_db.RegisterMessage(VisualTactileSensor)


# @@protoc_insertion_point(module_scope)
