# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/tools/cyber2pc/proto/Cyber2pcBatch.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.ts_common_msgs.proto_ts_wbd_msgs import TsWbd_pb2 as modules_dot_ts__common__msgs_dot_proto__ts__wbd__msgs_dot_TsWbd__pb2
from modules.ts_common_msgs.proto_custom_msgs.collect import tscompressedimage_pb2 as modules_dot_ts__common__msgs_dot_proto__custom__msgs_dot_collect_dot_tscompressedimage__pb2
from modules.ts_common_msgs.proto_visual_tactile_msgs import VisualTactileSensor_pb2 as modules_dot_ts__common__msgs_dot_proto__visual__tactile__msgs_dot_VisualTactileSensor__pb2
from modules.tools.cyber2pc.proto import ISuitD_pb2 as modules_dot_tools_dot_cyber2pc_dot_proto_dot_ISuitD__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/tools/cyber2pc/proto/Cyber2pcBatch.proto',
  package='apollo.tools.cyber2pc',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n0modules/tools/cyber2pc/proto/Cyber2pcBatch.proto\x12\x15\x61pollo.tools.cyber2pc\x1a\x34modules/ts_common_msgs/proto_ts_wbd_msgs/TsWbd.proto\x1aHmodules/ts_common_msgs/proto_custom_msgs/collect/tscompressedimage.proto\x1aJmodules/ts_common_msgs/proto_visual_tactile_msgs/VisualTactileSensor.proto\x1a)modules/tools/cyber2pc/proto/ISuitD.proto\"Z\n\x10\x42odyFeedbackData\x12\x14\n\x0c\x63hannel_name\x18\x01 \x01(\t\x12\x30\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x02 \x01(\x0b\x32\x1e.tars.ts_wbd_msgs.BodyFeedback\"\\\n\x0f\x43\x61meraImageData\x12\x14\n\x0c\x63hannel_name\x18\x01 \x01(\t\x12\x33\n\x05image\x18\x02 \x01(\x0b\x32$.tars.tscamera_msg.Tscompressedimage\"Z\n\tISuitData\x12\x14\n\x0c\x63hannel_name\x18\x01 \x01(\t\x12\x37\n\nisuit_data\x18\x02 \x01(\x0b\x32#.apollo.tools.cyber2pc.ISuitDSample\"p\n\x11VisualTactileData\x12\x14\n\x0c\x63hannel_name\x18\x01 \x01(\t\x12\x45\n\x0evisual_tactile\x18\x02 \x01(\x0b\x32-.tars.visual_tactile_msgs.VisualTactileSensor\"\x94\x02\n\rCyber2pcBatch\x12\x43\n\x12\x62ody_feedback_data\x18\x01 \x03(\x0b\x32\'.apollo.tools.cyber2pc.BodyFeedbackData\x12\x41\n\x11\x63\x61mera_image_data\x18\x02 \x03(\x0b\x32&.apollo.tools.cyber2pc.CameraImageData\x12\x34\n\nisuit_data\x18\x03 \x03(\x0b\x32 .apollo.tools.cyber2pc.ISuitData\x12\x45\n\x13visual_tactile_data\x18\x04 \x03(\x0b\x32(.apollo.tools.cyber2pc.VisualTactileData'
  ,
  dependencies=[modules_dot_ts__common__msgs_dot_proto__ts__wbd__msgs_dot_TsWbd__pb2.DESCRIPTOR,modules_dot_ts__common__msgs_dot_proto__custom__msgs_dot_collect_dot_tscompressedimage__pb2.DESCRIPTOR,modules_dot_ts__common__msgs_dot_proto__visual__tactile__msgs_dot_VisualTactileSensor__pb2.DESCRIPTOR,modules_dot_tools_dot_cyber2pc_dot_proto_dot_ISuitD__pb2.DESCRIPTOR,])




_BODYFEEDBACKDATA = _descriptor.Descriptor(
  name='BodyFeedbackData',
  full_name='apollo.tools.cyber2pc.BodyFeedbackData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_name', full_name='apollo.tools.cyber2pc.BodyFeedbackData.channel_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feedback', full_name='apollo.tools.cyber2pc.BodyFeedbackData.feedback', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=412,
)


_CAMERAIMAGEDATA = _descriptor.Descriptor(
  name='CameraImageData',
  full_name='apollo.tools.cyber2pc.CameraImageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_name', full_name='apollo.tools.cyber2pc.CameraImageData.channel_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='apollo.tools.cyber2pc.CameraImageData.image', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=506,
)


_ISUITDATA = _descriptor.Descriptor(
  name='ISuitData',
  full_name='apollo.tools.cyber2pc.ISuitData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_name', full_name='apollo.tools.cyber2pc.ISuitData.channel_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isuit_data', full_name='apollo.tools.cyber2pc.ISuitData.isuit_data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=598,
)


_VISUALTACTILEDATA = _descriptor.Descriptor(
  name='VisualTactileData',
  full_name='apollo.tools.cyber2pc.VisualTactileData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_name', full_name='apollo.tools.cyber2pc.VisualTactileData.channel_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='visual_tactile', full_name='apollo.tools.cyber2pc.VisualTactileData.visual_tactile', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=600,
  serialized_end=712,
)


_CYBER2PCBATCH = _descriptor.Descriptor(
  name='Cyber2pcBatch',
  full_name='apollo.tools.cyber2pc.Cyber2pcBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='body_feedback_data', full_name='apollo.tools.cyber2pc.Cyber2pcBatch.body_feedback_data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='camera_image_data', full_name='apollo.tools.cyber2pc.Cyber2pcBatch.camera_image_data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isuit_data', full_name='apollo.tools.cyber2pc.Cyber2pcBatch.isuit_data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='visual_tactile_data', full_name='apollo.tools.cyber2pc.Cyber2pcBatch.visual_tactile_data', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=715,
  serialized_end=991,
)

_BODYFEEDBACKDATA.fields_by_name['feedback'].message_type = modules_dot_ts__common__msgs_dot_proto__ts__wbd__msgs_dot_TsWbd__pb2._BODYFEEDBACK
_CAMERAIMAGEDATA.fields_by_name['image'].message_type = modules_dot_ts__common__msgs_dot_proto__custom__msgs_dot_collect_dot_tscompressedimage__pb2._TSCOMPRESSEDIMAGE
_ISUITDATA.fields_by_name['isuit_data'].message_type = modules_dot_tools_dot_cyber2pc_dot_proto_dot_ISuitD__pb2._ISUITDSAMPLE
_VISUALTACTILEDATA.fields_by_name['visual_tactile'].message_type = modules_dot_ts__common__msgs_dot_proto__visual__tactile__msgs_dot_VisualTactileSensor__pb2._VISUALTACTILESENSOR
_CYBER2PCBATCH.fields_by_name['body_feedback_data'].message_type = _BODYFEEDBACKDATA
_CYBER2PCBATCH.fields_by_name['camera_image_data'].message_type = _CAMERAIMAGEDATA
_CYBER2PCBATCH.fields_by_name['isuit_data'].message_type = _ISUITDATA
_CYBER2PCBATCH.fields_by_name['visual_tactile_data'].message_type = _VISUALTACTILEDATA
DESCRIPTOR.message_types_by_name['BodyFeedbackData'] = _BODYFEEDBACKDATA
DESCRIPTOR.message_types_by_name['CameraImageData'] = _CAMERAIMAGEDATA
DESCRIPTOR.message_types_by_name['ISuitData'] = _ISUITDATA
DESCRIPTOR.message_types_by_name['VisualTactileData'] = _VISUALTACTILEDATA
DESCRIPTOR.message_types_by_name['Cyber2pcBatch'] = _CYBER2PCBATCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BodyFeedbackData = _reflection.GeneratedProtocolMessageType('BodyFeedbackData', (_message.Message,), {
  'DESCRIPTOR' : _BODYFEEDBACKDATA,
  '__module__' : 'modules.tools.cyber2pc.proto.Cyber2pcBatch_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.cyber2pc.BodyFeedbackData)
  })
_sym_db.RegisterMessage(BodyFeedbackData)

CameraImageData = _reflection.GeneratedProtocolMessageType('CameraImageData', (_message.Message,), {
  'DESCRIPTOR' : _CAMERAIMAGEDATA,
  '__module__' : 'modules.tools.cyber2pc.proto.Cyber2pcBatch_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.cyber2pc.CameraImageData)
  })
_sym_db.RegisterMessage(CameraImageData)

ISuitData = _reflection.GeneratedProtocolMessageType('ISuitData', (_message.Message,), {
  'DESCRIPTOR' : _ISUITDATA,
  '__module__' : 'modules.tools.cyber2pc.proto.Cyber2pcBatch_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.cyber2pc.ISuitData)
  })
_sym_db.RegisterMessage(ISuitData)

VisualTactileData = _reflection.GeneratedProtocolMessageType('VisualTactileData', (_message.Message,), {
  'DESCRIPTOR' : _VISUALTACTILEDATA,
  '__module__' : 'modules.tools.cyber2pc.proto.Cyber2pcBatch_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.cyber2pc.VisualTactileData)
  })
_sym_db.RegisterMessage(VisualTactileData)

Cyber2pcBatch = _reflection.GeneratedProtocolMessageType('Cyber2pcBatch', (_message.Message,), {
  'DESCRIPTOR' : _CYBER2PCBATCH,
  '__module__' : 'modules.tools.cyber2pc.proto.Cyber2pcBatch_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.cyber2pc.Cyber2pcBatch)
  })
_sym_db.RegisterMessage(Cyber2pcBatch)


# @@protoc_insertion_point(module_scope)
