# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/tools/cyber2pc/proto/ISuitD.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/tools/cyber2pc/proto/ISuitD.proto',
  package='apollo.tools.cyber2pc',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n)modules/tools/cyber2pc/proto/ISuitD.proto\x12\x15\x61pollo.tools.cyber2pc\"K\n\tISuitDMag\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\r\n\x05\x66lags\x18\x02 \x01(\r\x12\n\n\x02mx\x18\x03 \x01(\x02\x12\n\n\x02my\x18\x04 \x01(\x02\x12\n\n\x02mz\x18\x05 \x01(\x02\"<\n\x0bISuitDAngle\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\r\n\x05\x66lags\x18\x02 \x01(\r\x12\x11\n\tangle_deg\x18\x03 \x01(\x02\"_\n\x0cISuitDAnchor\x12\x12\n\nseq_anchor\x18\x01 \x01(\r\x12\x14\n\x0c\x61nchor_flags\x18\x02 \x01(\r\x12\x14\n\x0cts_anchor_ms\x18\x03 \x01(\x03\x12\x0f\n\x07\x62\x61\x64_crc\x18\x04 \x01(\r\"\xcf\x02\n\nISuitDPerf\x12\x17\n\x0frx_frames_total\x18\x01 \x01(\x04\x12\x16\n\x0erx_bytes_total\x18\x02 \x01(\x04\x12\x11\n\tgap_count\x18\x03 \x01(\x04\x12\x12\n\nlost_count\x18\x04 \x01(\x04\x12\x11\n\tdup_count\x18\x05 \x01(\x04\x12\x12\n\nerr_resync\x18\x06 \x01(\x04\x12\x1a\n\x12ring_overrun_count\x18\x07 \x01(\x04\x12\x1a\n\x12per_id_mono_errors\x18\x08 \x01(\x04\x12\x11\n\tlat_count\x18\t \x01(\x04\x12\x13\n\x0blat_mean_ms\x18\n \x01(\x01\x12\x12\n\nlat_min_ms\x18\x0b \x01(\x01\x12\x12\n\nlat_p50_ms\x18\x0c \x01(\x01\x12\x12\n\nlat_p95_ms\x18\r \x01(\x01\x12\x12\n\nlat_p99_ms\x18\x0e \x01(\x01\x12\x12\n\nlat_max_ms\x18\x0f \x01(\x01\"\xeb\x02\n\x0cISuitDSample\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\x10\n\x08t_mcu_ms\x18\x02 \x01(\x03\x12\n\n\x02\x61x\x18\x03 \x01(\x02\x12\n\n\x02\x61y\x18\x04 \x01(\x02\x12\n\n\x02\x61z\x18\x05 \x01(\x02\x12\n\n\x02gx\x18\x06 \x01(\x02\x12\n\n\x02gy\x18\x07 \x01(\x02\x12\n\n\x02gz\x18\x08 \x01(\x02\x12-\n\x03mag\x18\t \x01(\x0b\x32 .apollo.tools.cyber2pc.ISuitDMag\x12\x31\n\x05\x61ngle\x18\n \x01(\x0b\x32\".apollo.tools.cyber2pc.ISuitDAngle\x12\x33\n\x06\x61nchor\x18\x0b \x01(\x0b\x32#.apollo.tools.cyber2pc.ISuitDAnchor\x12/\n\x04perf\x18\x0c \x01(\x0b\x32!.apollo.tools.cyber2pc.ISuitDPerf\x12\x14\n\x0c\x65xpected_seq\x18\r \x01(\r\x12\x16\n\x0elocked_aligned\x18\x0e \x01(\x08'
)




_ISUITDMAG = _descriptor.Descriptor(
  name='ISuitDMag',
  full_name='apollo.tools.cyber2pc.ISuitDMag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='apollo.tools.cyber2pc.ISuitDMag.seq', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flags', full_name='apollo.tools.cyber2pc.ISuitDMag.flags', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mx', full_name='apollo.tools.cyber2pc.ISuitDMag.mx', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='my', full_name='apollo.tools.cyber2pc.ISuitDMag.my', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mz', full_name='apollo.tools.cyber2pc.ISuitDMag.mz', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=143,
)


_ISUITDANGLE = _descriptor.Descriptor(
  name='ISuitDAngle',
  full_name='apollo.tools.cyber2pc.ISuitDAngle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='apollo.tools.cyber2pc.ISuitDAngle.seq', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flags', full_name='apollo.tools.cyber2pc.ISuitDAngle.flags', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angle_deg', full_name='apollo.tools.cyber2pc.ISuitDAngle.angle_deg', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=205,
)


_ISUITDANCHOR = _descriptor.Descriptor(
  name='ISuitDAnchor',
  full_name='apollo.tools.cyber2pc.ISuitDAnchor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq_anchor', full_name='apollo.tools.cyber2pc.ISuitDAnchor.seq_anchor', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='anchor_flags', full_name='apollo.tools.cyber2pc.ISuitDAnchor.anchor_flags', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ts_anchor_ms', full_name='apollo.tools.cyber2pc.ISuitDAnchor.ts_anchor_ms', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bad_crc', full_name='apollo.tools.cyber2pc.ISuitDAnchor.bad_crc', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=302,
)


_ISUITDPERF = _descriptor.Descriptor(
  name='ISuitDPerf',
  full_name='apollo.tools.cyber2pc.ISuitDPerf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rx_frames_total', full_name='apollo.tools.cyber2pc.ISuitDPerf.rx_frames_total', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rx_bytes_total', full_name='apollo.tools.cyber2pc.ISuitDPerf.rx_bytes_total', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gap_count', full_name='apollo.tools.cyber2pc.ISuitDPerf.gap_count', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lost_count', full_name='apollo.tools.cyber2pc.ISuitDPerf.lost_count', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dup_count', full_name='apollo.tools.cyber2pc.ISuitDPerf.dup_count', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='err_resync', full_name='apollo.tools.cyber2pc.ISuitDPerf.err_resync', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ring_overrun_count', full_name='apollo.tools.cyber2pc.ISuitDPerf.ring_overrun_count', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_id_mono_errors', full_name='apollo.tools.cyber2pc.ISuitDPerf.per_id_mono_errors', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lat_count', full_name='apollo.tools.cyber2pc.ISuitDPerf.lat_count', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lat_mean_ms', full_name='apollo.tools.cyber2pc.ISuitDPerf.lat_mean_ms', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lat_min_ms', full_name='apollo.tools.cyber2pc.ISuitDPerf.lat_min_ms', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lat_p50_ms', full_name='apollo.tools.cyber2pc.ISuitDPerf.lat_p50_ms', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lat_p95_ms', full_name='apollo.tools.cyber2pc.ISuitDPerf.lat_p95_ms', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lat_p99_ms', full_name='apollo.tools.cyber2pc.ISuitDPerf.lat_p99_ms', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lat_max_ms', full_name='apollo.tools.cyber2pc.ISuitDPerf.lat_max_ms', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=640,
)


_ISUITDSAMPLE = _descriptor.Descriptor(
  name='ISuitDSample',
  full_name='apollo.tools.cyber2pc.ISuitDSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='apollo.tools.cyber2pc.ISuitDSample.seq', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='t_mcu_ms', full_name='apollo.tools.cyber2pc.ISuitDSample.t_mcu_ms', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ax', full_name='apollo.tools.cyber2pc.ISuitDSample.ax', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ay', full_name='apollo.tools.cyber2pc.ISuitDSample.ay', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='az', full_name='apollo.tools.cyber2pc.ISuitDSample.az', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gx', full_name='apollo.tools.cyber2pc.ISuitDSample.gx', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gy', full_name='apollo.tools.cyber2pc.ISuitDSample.gy', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gz', full_name='apollo.tools.cyber2pc.ISuitDSample.gz', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mag', full_name='apollo.tools.cyber2pc.ISuitDSample.mag', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angle', full_name='apollo.tools.cyber2pc.ISuitDSample.angle', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='anchor', full_name='apollo.tools.cyber2pc.ISuitDSample.anchor', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='perf', full_name='apollo.tools.cyber2pc.ISuitDSample.perf', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expected_seq', full_name='apollo.tools.cyber2pc.ISuitDSample.expected_seq', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='locked_aligned', full_name='apollo.tools.cyber2pc.ISuitDSample.locked_aligned', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=643,
  serialized_end=1006,
)

_ISUITDSAMPLE.fields_by_name['mag'].message_type = _ISUITDMAG
_ISUITDSAMPLE.fields_by_name['angle'].message_type = _ISUITDANGLE
_ISUITDSAMPLE.fields_by_name['anchor'].message_type = _ISUITDANCHOR
_ISUITDSAMPLE.fields_by_name['perf'].message_type = _ISUITDPERF
DESCRIPTOR.message_types_by_name['ISuitDMag'] = _ISUITDMAG
DESCRIPTOR.message_types_by_name['ISuitDAngle'] = _ISUITDANGLE
DESCRIPTOR.message_types_by_name['ISuitDAnchor'] = _ISUITDANCHOR
DESCRIPTOR.message_types_by_name['ISuitDPerf'] = _ISUITDPERF
DESCRIPTOR.message_types_by_name['ISuitDSample'] = _ISUITDSAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ISuitDMag = _reflection.GeneratedProtocolMessageType('ISuitDMag', (_message.Message,), {
  'DESCRIPTOR' : _ISUITDMAG,
  '__module__' : 'modules.tools.cyber2pc.proto.ISuitD_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.cyber2pc.ISuitDMag)
  })
_sym_db.RegisterMessage(ISuitDMag)

ISuitDAngle = _reflection.GeneratedProtocolMessageType('ISuitDAngle', (_message.Message,), {
  'DESCRIPTOR' : _ISUITDANGLE,
  '__module__' : 'modules.tools.cyber2pc.proto.ISuitD_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.cyber2pc.ISuitDAngle)
  })
_sym_db.RegisterMessage(ISuitDAngle)

ISuitDAnchor = _reflection.GeneratedProtocolMessageType('ISuitDAnchor', (_message.Message,), {
  'DESCRIPTOR' : _ISUITDANCHOR,
  '__module__' : 'modules.tools.cyber2pc.proto.ISuitD_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.cyber2pc.ISuitDAnchor)
  })
_sym_db.RegisterMessage(ISuitDAnchor)

ISuitDPerf = _reflection.GeneratedProtocolMessageType('ISuitDPerf', (_message.Message,), {
  'DESCRIPTOR' : _ISUITDPERF,
  '__module__' : 'modules.tools.cyber2pc.proto.ISuitD_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.cyber2pc.ISuitDPerf)
  })
_sym_db.RegisterMessage(ISuitDPerf)

ISuitDSample = _reflection.GeneratedProtocolMessageType('ISuitDSample', (_message.Message,), {
  'DESCRIPTOR' : _ISUITDSAMPLE,
  '__module__' : 'modules.tools.cyber2pc.proto.ISuitD_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.cyber2pc.ISuitDSample)
  })
_sym_db.RegisterMessage(ISuitDSample)


# @@protoc_insertion_point(module_scope)
