# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/ts_common_msgs/proto_basic_msgs/time.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/ts_common_msgs/proto_basic_msgs/time.proto',
  package='tars.basic_msgs',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n2modules/ts_common_msgs/proto_basic_msgs/time.proto\x12\x0ftars.basic_msgs\"!\n\x04time\x12\x0b\n\x03sec\x18\x01 \x02(\r\x12\x0c\n\x04nsec\x18\x02 \x02(\r'
)




_TIME = _descriptor.Descriptor(
  name='time',
  full_name='tars.basic_msgs.time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sec', full_name='tars.basic_msgs.time.sec', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nsec', full_name='tars.basic_msgs.time.nsec', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['time'] = _TIME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

time = _reflection.GeneratedProtocolMessageType('time', (_message.Message,), {
  'DESCRIPTOR' : _TIME,
  '__module__' : 'modules.ts_common_msgs.proto_basic_msgs.time_pb2'
  # @@protoc_insertion_point(class_scope:tars.basic_msgs.time)
  })
_sym_db.RegisterMessage(time)


# @@protoc_insertion_point(module_scope)
